version: "3.8"
services:
  db:
    image: postgres
    env_file: postgres.env
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  app:
    depends_on:
      - db
    restart: always
    build: .
    expose:
      - "8080"
    ports:
      - 8080:8080
